version: "3"
services:
  server:
    build:
      context: .
    restart: on-failure
    ports:
      - "8092:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pizza_project?useSSL=false&serverTimezone=UTC
      - spring.datasource.password=00000000
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.31
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=00000000
      - MYSQL_DATABASE=pizza_project
    ports:
      - "3309:3306"
    volumes:
      - db:/var/lib/mysql

networks:
  springmysql-net:

volumes:
  db: