version: "3"
services:
  mysqldb:
    image: mysql:8.0.31
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=00000000
      - MYSQL_DATABASE=pizza_project
    ports:
      - "3309:3306"
    volumes:
      - db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - mysqldb
    build:
      context: .
    restart: on-failure
    ports:
      - "8092:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pizza_project?useSSL=false&serverTimezone=UTC
      - spring.datasource.user=root
      - spring.datasource.password=00000000


volumes:
  db: